#! /bin/env bash

# Base project directory
export PROJECTDIR="$HOME/Projects"

# Set my editors
export GUI_EDITOR="code"
EDITOR=$(which nvim);
export EDITOR

# Set paths
export GOPATH="$PROJECTDIR/Go"
export PATH="$CPAN_HOME/bin:$HOME/bin:$GOPATH/bin"
export PATH="$HOME/bin:/usr/lib/ccache/bin/:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/opt/bin:/usr/bin/core_perl:$PATH"
export ZSH=$HOME/.oh-my-zsh

# Larger history (allow 32³ entries; default is 500)
export HISTSIZE=50000000;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;

## EDITOR CONFIG ##
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi


## ZSH USER CONFIG ##
export COMPLETION_WAITING_DOTS="true"

## OH-MY-ZSH ##
# Tell oh-my-zsh to auto update and not to bother prompting me
export DISABLE_UPDATE_PROMPT=true

export PYTHONIOENCODING='UTF-8'

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
GPG_TTY=$(tty);
export GPG_TTY

# Keep showing man page after exit
export MANPAGER='less -X';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Dotfiles
export DOTFILES_DIR="$PROJECTDIR/mattyjones/kraken";
