#! /bin/env zsh

## THEMES ##
ZSH_THEME="robbyrussell"

## PLUGINS ##
plugins=()

## SHH AGENT CONFIG ##
key_file=~/.ssh/id_rsa
ssh-add >/dev/null 2>&1

## EDITOR CONFIG ##
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi

## USER CONFIG ##
COMPLETION_WAITING_DOTS="true"

ulimit -S -n 8192

## INCLUDES ##
source $HOME/.alias   # alias functions
source $HOME/.exports  # env exports
source $HOME/.secrets   # env secrets
source $HOME/.functions # env functions
source $ZSH/oh-my-zsh.sh

source /usr/local/share/chruby/chruby.sh
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# https://starship.rs
eval "$(starship init zsh)"

test -r ~/.dir_colors && eval $(dircolors ~/.dir_colors)

# Append to the Bash history file, rather than overwriting it

shopt -s histappend
