#! /bin/bash

# TODO: set these in Ansible

## ALIASES ##

# Copy a public key to the clipboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"

# Copy a provate key to the clipboard
alias prikey="more ~/.ssh/id_rsa | pbcopy | echo '=> Private key copied to pasteboard.'"

# Flush Directory Service cache
alias flush-dns='sudo killall -HUP mDNSResponder'

# IP addresses
alias pubip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="sudo ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias ips="sudo ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Safe auto-correct by default
alias ra="rubocop -a "

# Do not glob by default, required for zsh
alias rake="noglob rake"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Shortcut to for golang src directory
alias golang='cd $PROJECTDIR/Go/src/'

# I use neovim not vim
alias vim='nvim'

# Clear the screen
alias cls='clear'

alias kraken='ansible-playbook -i localhost -K site.yml'

# Don't use cp in modern times
alias cp='rsync --progress -avz'

# Default to colored output
alias ls='ls -C'

# Always enable colored `grep` output
alias grep='grep --color=auto '

# What cool things are running on the box
alias rtc='which awk perl python python3 python3 ruby lua gcc cc vi vim nmap find netcat nc wget tftp ftp 2>/dev/null'

# Start a webserver
alias webserver="sudo python2 -m SimpleHTTPServer 80"

# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"

# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

alias brewclean='brew cleanup --prune=all -s && rm -rf $(brew --cache)'

# Get the weather
alias weather="curl -4 http://wttr.in/$1"

# Shortcuts
alias dls='cd $HOME/Downloads'
alias dotfiles='cd $DOTFILES_DIR'
alias dtop='cd $HOME/Desktop'
alias lib='cd $HOME/Library'
alias proj='cd $HOME/Projects'

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
# shellcheck disable=2139
alias emptytrash=" \
  sudo rm -rfv /private/var/log/asl/*.asl; \
  sqlite3 $HOME/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent' \
"

# Get macOS Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
# shellcheck disable=1004
alias update='\
  sudo softwareupdate -i -a; \
  brew update; \
  brew upgrade; \
  brew cleanup; \
  sudo gem update --system; \
  sudo gem update; \
  sudo gem cleanup; \
'
