#! /bin/env bash

# TODO: set these in Ansible

# Base project directory
export PROJECTDIR="$HOME/Projects"

# Set my editors
export GUI_EDITOR="code"
EDITOR=$(which nvim);
export EDITOR

# Set paths
# export CPAN_HOME=/usr/local/Cellar/cpanminus/<version>
export CPAN_HOME="" # Perl Placeholder
export GOPATH="$PROJECTDIR/Go"
export PATH="$CPAN_HOME/bin:$HOME/bin:$GOPATH/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin"
export ZSH=$HOME/.oh-my-zsh

# Larger history (allow 32³ entries; default is 500)
export HISTSIZE=50000000;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
GPG_TTY=$(tty);
export GPG_TTY


# Perl
# export PATH="$HOME/perl5/bin${PATH:+:${PATH}}"; export PATH;
# export PERL5LIB="$HOME/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
# export PERL_LOCAL_LIB_ROOT="$HOME/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
# export PERL_MB_OPT="--install_base" "${HOME}"/perl5\; export PERL_MB_OPT;
# export PERL_MM_OPT="INSTALL_BASE=$HOME/perl5"; export PERL_MM_OPT;

# Keep showing man page after exit
export MANPAGER='less -X';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Dotfiles
export DOTFILES_DIR="$PROJECTDIR/mattyjones/kraken";
