#! /bin/env bash

# TODO: Move this to Ansible vault

#-------------------- VPN --------------------#
# Configure vpn setings                       #
#                                             #
#---------------------------------------------#
export VPN_SHARED_SECRET=""
export VPN_USER=""
export VPN_PWD=""

#--------------- DIGITAL OCEAN ---------------#
# Digital Ocean tokens and security           #
# credentials                                 #
#                                             #
#---------------------------------------------#
export DO_API_TOKEN=""
export DO_SSH_FINGERPRINT=""

#-------------------- AWS --------------------#
# AWS tokens and security credentials         #
#                                             #
#---------------------------------------------#
export AWS_SECRET_KEY=""
export AWS_ACCESS_KEY=""
export AWS_DEFAULT_REGION="us-east-1"

#---------------- NETWORKING -----------------#
# Network configuration and security          #
#                                             #
#---------------------------------------------#
export GLOBAL_DNS="8.8.8.8 8.8.4.4"

#--------------- Applications ----------------#
# Application specific settings               #
#                                             #
#---------------------------------------------#

#--- PyPi ---#
export TEST_TOKEN=""
export TEST_NAME=""

#--- Terraform ---#
export TF_LOG=1
export TF_VAR_do_token=""
export TF_VAR_pub_key=""
export TF_VAR_pvt_key=""
export TF_VAR_ssh_fingerprint=""

#--- LIFX ---#
export LIFX_TOKEN=""

#--- Vault ---#

#--- VSphere ---#
export VSPHERE_USER=""
export VSPHERE_PASS=""

#--- VSCE ---#
export Access_Token=""

#--- Artifactory ---#

#--- Git ---#
export GITHUB_API_TOKEN=""
export GITLAB_API_YOKEN=""

#--- LDAP ---#
