
global:
  build_masscan: true
  enable_zsh: true
  configure_vm_share: true
  share_path: /mnt
  share_name: sharefs
  install_base_pentest_tools: true
  install_development_pkgs: true
  install_vmware_pkgs: true
  install_gui: true
  overwrite_existing_configs: true

packages:  
  blackarch:
    install: true
  gui:
    install: false
# break out by library and have a selection for all
