
global:

packages:
  eye_candy:
    install: false
  gui:
    install: false
  networking:
    install : false
  pentest_tools:
    install: false
  security:
    install: false
  system:
    install: false
  editors:
    install : false
  development:
    install : false
  shell:
    install: false
  terminal:
    install: false
  vmware:
    install: false

system:
  release_branch: "testing"
  reboot_on_finish: false

