---
- name: Install alacritty
  ansible.builtin.apt:
    name: alacritty
    state: latest

- name: Install Fira Code 
  ansible.builtin.apt:
    name: fonts-firacode
    state: latest

# TODO: need to set the directoory/user dynamically based on other tasks
- name: Copy the configuration file
  copy:
    src: files/alacritty
    dest: /home/matt/.alacritty

# # Alacritty is my current terminal emulator for all platforms. It is
# # very fast, easy to configure, and has all the options I need. When it starts
# # I launch tmux automagically to allow me the flexibility I need. See the
# # config file for more details.
# configure_alacritty() {
#   ln -s "$cwd/alacritty/_alacritty.yml" "$HOME/.alacritty.yml"

#   return 0
# }

# ## install
# sudo apt install curl git cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# source $HOME/.cargo/env
# rustup override set stable
# rustup update stable
# git clone https://github.com/alacritty/alacritty.git
# cd alacritty
# cargo build --release
# cd target/release
# mv alacritty /usr/local/bin

# ## setup

#   git clone https://github.com/alacritty/alacritty.git /tmp/alacritty
#   cd /tmp/alacritty || return 1
#   cargo build --release
#   cd target/release || return 1
#   sudo  mv alacritty /usr/local/bin
#   sudo rm -rf /tmp/alacritty



# ##-------------------------- Terminal ----------------------##

# # install_alacritty installs and drops the configuration file for alacritty. Alacritty is my current
# # terminal emulator for all platforms. It's very fast, easy to configure, and has all the options I need.
# # When it starts I launch tmux automagically to allow me the flexibility I need. See the config file for more details.
# install_alacritty() {

#   # all installation methods currently require rust to be installed
#   install_rust

#   # ensure dependencies are present for building
#   local pkgs=("cmake" "libfontconfig-dev")
#   package_install "${pkgs[@]}"
#   check_error $?

#   git clone https://github.com/alacritty/alacritty.git /tmp/alacritty
#   cd /tmp/alacritty || return 1
#   cargo build --release
#   cd target/release || return 1
#   sudo  mv alacritty /usr/local/bin
#   sudo rm -rf /tmp/alacritty

#   # Need to link the config file, not copy it
#   ln -s "$cwd/alacritty/_alacritty.yml" "$HOME/.alacritty.yml"

#   # FIXME: fix the yaml to call tmux when started is borked

#   # TODO: need to set it as the default terminal program in the GUI

#   return 0
# }