---

# TODO: better comments
# TODO: need to set it as the default terminal program in the GUI
##-------------------------- Terminal ----------------------##

- name: Install alacritty
  ansible.builtin.apt:
    name: alacritty
    state: latest
  become: true

- name: Install Fira Code
  ansible.builtin.apt:
    name: fonts-firacode
    state: latest
  become: true

# TODO: need to set the directoory/user dynamically based on other tasks
- name: Copy the configuration file
  copy:
    src: alacritty.yml
    dest: /home/matt/.alacritty.yml

