---
# TODO: Set the branch to testing or ensure it is already set

- name: Update apt cache 
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: true

- name: Purge config files not needed
  ansible.builtin.apt:
    purge: true
  become: true

- name: Remove unnecessary packages 
  ansible.builtin.apt:
    autoremove: true
  become: true

- name: Remove packages that can't be downloaded 
  ansible.builtin.apt:
    autoclean: true
  become: true

- name: Clean the local repo of packages
  ansible.builtin.apt:
    clean: true
  become: true

